"""Freeze the final churn model and its decision policy (Phase 9C).

Usage (from the repository root):

    uv run python scripts/build_split.py --verify     # prove the split
    uv run python scripts/freeze_model.py             # fit, persist, freeze
    uv run python scripts/freeze_model.py --verify    # check the freeze, change nothing

Writes:
    artifacts/model/churn_pipeline.joblib   (regenerable, not versioned)
    reports/decision_policy.json            (the versioned freeze contract)
    reports/model_freeze_report.md

Only the frozen training pool is loaded. The holdout is never read.

Nothing is decided here. The estimator was selected in Phase 8B, the calibration
policy in Phase 9A and the threshold in Phase 9B; this script fits that estimator
on the whole training pool, persists it, and writes down with fingerprints what
will later be applied to the holdout. No metric is computed from the fit and no
performance figure is produced.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import numpy as np

from churn.config import PROJECT_ROOT, get_config
from churn.data.loader import RawDatasetMismatchError
from churn.modeling.calibration_results import (
    FrozenCandidateMismatchError,
    verify_frozen_candidate,
)
from churn.modeling.calibration_results import load_results as load_calibration_results
from churn.modeling.freeze import (
    PIPELINE_PATH,
    IntegrityCheck,
    IntegrityError,
    apply_decision_rule,
    dump_pipeline,
    file_digest,
    fit_final_pipeline,
    load_pipeline,
    model_fingerprint,
    positive_probability,
)
from churn.modeling.freeze_results import (
    POLICY_PATH,
    UPSTREAM_ARTEFACTS,
    DecisionPolicy,
    build_decision_policy,
    load_decision_policy,
    verify_decision_policy,
    verify_or_raise,
    write_decision_policy,
)
from churn.modeling.metrics import positive_prevalence
from churn.modeling.threshold_results import (
    CalibrationPolicyMismatchError,
    verify_calibration_policy,
)
from churn.modeling.threshold_results import load_results as load_threshold_results
from churn.modeling.tuning_results import load_results as load_tuning_results
from churn.preprocessing.contracts import build_feature_matrix
from churn.preprocessing.manifest import (
    SplitManifestMismatchError,
    load_split_manifest,
    verify_split_manifest,
)
from churn.preprocessing.splitting import load_training_pool
from churn.preprocessing.target import encode_target

logger = logging.getLogger("freeze_model")

REPORT_PATH = PROJECT_ROOT / "reports" / "model_freeze_report.md"

#: Rows of the training pool used to demonstrate that a reloaded pipeline scores
#: identically. A demonstration of serialisation fidelity, never an evaluation:
#: no label is read and no metric is computed.
RELOAD_PROBE_ROWS = 256


def _check_table(checks: list[IntegrityCheck]) -> str:
    lines = ["| Check | Result | Observed |", "| --- | --- | --- |"]
    for check in checks:
        detail = check.detail.replace("|", "\\|")
        verdict = "**PASS**" if check.passed else "**FAIL**"
        lines.append(f"| `{check.name}` | {verdict} | {detail} |")
    return "\n".join(lines)


def _digest_table(policy: DecisionPolicy) -> str:
    digests = policy.provenance["upstream_artefact_digests"]
    lines = ["| Upstream artefact | SHA-256 |", "| --- | --- |"]
    for artefact, digest in digests.items():
        lines.append(f"| `{artefact}` | `{digest[:16]}…` |")
    return "\n".join(lines)


def build_report(policy: DecisionPolicy, checks: list[IntegrityCheck], reload_note: str) -> str:
    """Render the Phase 9C report. Every value comes from the freeze record.

    The report carries **no wall-clock metadata**, per the convention recorded in
    `CLAUDE.md`: it is a pure function of its inputs, so a rerun on an unchanged
    repository reproduces it byte for byte and any diff is a real change.
    """
    model = policy.model
    contract = policy.feature_contract
    rule = policy.decision_rule
    artefact = policy.artifacts
    threshold = policy.threshold.final_threshold

    return f"""# Final Model & Decision Policy Freeze — Telco Customer Churn (Phase 9C)

- Generated by: `scripts/freeze_model.py`
- Machine-readable contract: `reports/decision_policy.json`
- Raw SHA-256: `{policy.raw_sha256}`
- Training partition fingerprint: `{policy.training_ids_sha256}`

> **This report carries no generation date.** It is a pure function of its
> inputs, so re-running the generator on an unchanged repository reproduces it
> byte for byte and any diff is a real change. Git records when it was produced.

> **No holdout/test performance has been measured at this stage.** Nothing in
> this report is a metric, because this phase computes none.

---

## 1. What this phase is, and what it is not

Phase 9C **decides nothing**. Every choice it writes down was made and closed
earlier:

| Decision | Made in | Value |
| --- | --- | --- |
| Model family and hyperparameters | `{model.selected_in}` | `{model.estimator}`, frozen |
| Calibration policy | `{policy.calibration.decided_in}` | \
**{policy.calibration.calibration_policy}** |
| Threshold policy | `{policy.threshold.decided_in}` | \
**{policy.threshold.threshold_policy}** |
| Threshold | `{policy.threshold.decided_in}` | **{threshold}** |

What is new here is one fitted object plus one contract, so that after the
holdout is opened it stays provable that what was evaluated is what was frozen
beforehand. `reopened_decisions` in the record is `{policy.reopened_decisions}`.

## 2. Frozen model

| Property | Value |
| --- | --- |
| Estimator | `{model.estimator}` |
| Builder | `{model.builder}` |
| Pipeline builder | `{model.pipeline_builder}` |
| Selected in | `{model.selected_in}` |
| Hyperparameters | \
{", ".join(f"`{k}={v}`" for k, v in model.hyperparameters.items())} |
| Reopened here | {model.reopened_here} |
| Preprocessing | {" → ".join(model.preprocessing["steps"])} |
| Transformed columns | {model.preprocessing["n_transformed_features"]} |
| Seed | {policy.random_seed} |

### The final fit

| Property | Value |
| --- | --- |
| Partition | {model.fitted_on["partition"]} |
| Loader | `{model.fitted_on["loader"]}` |
| Rows | {model.fitted_on["n_rows"]:,} |
| Fraction of the pool used | {model.fitted_on["fraction_of_pool_used"]} |
| Positive prevalence | {model.fitted_on["positive_prevalence"]:.4f} |
| Converged | {model.convergence["converged"]} |
| Iterations | {model.convergence["n_iter"]} of {model.convergence["max_iter"]} |

**Fitting on the whole pool is not a change of protocol.** Every earlier phase
fitted this same pipeline on four fifths of the pool at a time because it needed
a validation fold to measure something. That need ends once the configuration is
frozen: this fit measures nothing, it materialises a decision. No metric was
computed from it, and none could change anything if it had been.

The sequence, with no branch anywhere in it:

```text
frozen training pool  ({model.fitted_on["n_rows"]:,} rows)
        ↓
prepare_features        (contract validation, canonical column order)
        ↓
build_modern_logistic_pipeline()
        ↓
fit
        ↓
persist                 ({artefact.pipeline_path})
        ↓
freeze decision policy  (reports/decision_policy.json)
```

## 3. Frozen representation

| Property | Value |
| --- | --- |
| Entry point | `{contract.entry_point}` |
| Features | {contract.n_features} original |
| Numeric ({len(contract.numeric)}) | {", ".join(f"`{name}`" for name in contract.numeric)} |
| Categorical | {len(contract.categorical)} columns |
| Engineered | {contract.engineered or "none"} |
| Feature-name fingerprint | `{contract.feature_names_sha256[:16]}…` |
| Transformed columns | {contract.n_transformed_features} |
| Transformed-name fingerprint | `{contract.transformed_feature_names_sha256[:16]}…` |

### The feature-preparation boundary

{contract.boundary}.

That boundary was fixed in Phase 4 and is **not moved here**. The persisted
object is not a self-validating endpoint: it assumes its input already satisfies
the contract. Turning that into a public prediction interface — payload schema,
validation errors, response shape — is Phase 11's subject, and nothing of it is
anticipated in this phase.

### The full inference function, and why the `.joblib` does not cover it

```text
{
        chr(10).join(
            f"{'    ↓' if index else ''}{chr(10) if index else ''}{step}"
            for index, step in enumerate(policy.inference_contract.chain)
        )
    }
```

**Only the middle of that chain is inside the serialised file.** Two links are
not, and both can change a prediction while every fingerprint of the model itself
stays identical:

- **`prepare_features` runs before the pipeline is reached.** {policy.inference_contract.note}.
- **`TotalChargesCleaner` is inside the pipeline, but only by reference.** A
  pickle stores fitted *state* — arrays, hyperparameters — while classes are
  stored as a module path: the stream carries
  `churn.preprocessing.transformers`, and unpickling imports whatever that module
  currently defines. Editing its `transform` changes what the loaded pipeline
  computes, with `pipeline_sha256` and `model_fingerprint_sha256` both unmoved.

Section 8 closes both gaps by fingerprinting source.

## 4. Calibration policy

**`calibration_policy = {policy.calibration.calibration_policy}`** — \
`calibrated: {policy.calibration.calibrated}`.

{policy.calibration.note}.

The probability the decision rule acts on is therefore
`{policy.calibration.probability_expression}` of the uncalibrated logistic
regression. No calibrator is present in the persisted object, and an integrity
check asserts its absence rather than assuming it.

## 5. Threshold policy

**`threshold_policy = {policy.threshold.threshold_policy}`**

```text
final_threshold = {threshold}
```

{policy.threshold.note}.

Stored **unrounded** (`rounded: {policy.threshold.rounded}`). A threshold rounded
in the sixth decimal can move customers across the decision boundary, so the
value recorded here is the value that will be applied, at full double precision.

## 6. Decision rule

```text
predict churn if P(Churn = 1 | x) >= {threshold}
```

| Property | Value |
| --- | --- |
| Expression | `{rule.expression}` |
| Comparison | `{rule.comparison}` |
| Probability | `{rule.probability_expression}` |
| Fitted classes | `{rule.classes}` |
| Positive class label | `{rule.positive_class_label}` ({rule.positive_class_meaning}) |
| Positive class column | `{rule.positive_class_column}` |
| Negative class label | `{rule.negative_class_label}` |

Two things are written down that are usually left implicit, because both are
places where a freeze can be silently wrong:

- **the boundary.** {rule.boundary_note}. `>` and `>=` differ on exactly the
  customers whose probability equals the threshold; with a threshold read from a
  stored decimal that set is usually empty and occasionally is not, and "usually
  empty" is not a specification;
- **the column.** The positive-class column is resolved from `classes_`, never
  assumed to be column 1. The assumption happens to hold for this estimator and
  is still the wrong thing to record: reading the wrong column would invert every
  decision without raising anything.

## 7. Persisted artefacts and fingerprints

| Property | Value |
| --- | --- |
| Pipeline | `{artefact.pipeline_path}` |
| Size | {artefact.pipeline_bytes:,} bytes |
| Serialisation | `joblib` {artefact.serialization["joblib_version"]}, \
protocol {artefact.serialization["protocol"]}, compress {artefact.serialization["compress"]} |
| `pipeline_sha256` | `{artefact.pipeline_sha256}` |
| `model_fingerprint_sha256` | `{artefact.model_fingerprint_sha256}` |
| Authoritative | `{artefact.authoritative_fingerprint}` |
| Versioned in git | {artefact.versioned_in_git} |

**Two fingerprints, answering different questions.**

- **`model_fingerprint_sha256`** hashes the *learned parameters* — transformed
  feature names, coefficients, intercept, `n_iter_`, scaler mean/scale/variance,
  encoder categories — under a canonical JSON encoding in which every double
  round-trips exactly. This is the **identity of the model**: two objects with
  this value make the same predictions, whatever pickle protocol or library build
  produced them. It is the check that decides.
- **`pipeline_sha256`** hashes the file bytes. It catches a corrupted or swapped
  file, but it is a property of the *file*, not of the model, and it is not
  guaranteed to survive a change of environment.

**The binary is not committed, and that is deliberate.** `artifacts/` is
git-ignored by an existing repository convention for regenerable model files.
{artefact.note}. That is a stronger guarantee than storing the binary would be:
it proves the frozen object is reproducible from source, rather than merely
present. The *contract* — this policy, with both fingerprints — is versioned, and
that is what makes the freeze provable.

`protocol` and `compress` are pinned rather than left at their defaults. A future
interpreter raising `pickle.DEFAULT_PROTOCOL` would otherwise change every byte
of the file, and its digest, without anything about the model having changed.

## 8. Provenance

{_digest_table(policy)}

Digests of the artefacts this freeze is anchored to. A reference by name says
which file was meant; a digest says which bytes were read.

| Reference | Artefact | Experiment |
| --- | --- | --- |
{
        chr(10).join(
            f"| {key} | `{value['artefact']}` | `{value['experiment']}` |"
            for key, value in policy.provenance["references"].items()
        )
    }

| Property | Value |
| --- | --- |
| Raw dataset | `{policy.raw_sha256[:16]}…` |
| Training partition | `{policy.training_ids_sha256[:16]}…` |
| Split manifest | `{policy.provenance["split"]["manifest"]}` |
| Configuration | `{policy.provenance["configuration"]}` |
| Python | {policy.environment["python"]} |
| scikit-learn | {policy.environment["scikit_learn"]} |
| numpy | {policy.environment["numpy"]} |
| pandas | {policy.environment["pandas"]} |
| joblib | {policy.environment["joblib"]} |

{policy.provenance["split"]["note"]}.

### Code provenance — freezing the inference function, not only the object

**Strategy:** {policy.code_provenance.strategy}.

**Digest definition:** {policy.code_provenance.digest_definition}.

> **Caveat, stated plainly.** {policy.code_provenance.caveat}.

`prepare_features` additionally carries a **function-level** digest
(`{policy.inference_contract.prepare_features_source_sha256[:16]}…`, from
`inspect.getsource`). It is a **diagnostic, not the gate**: when a freeze fails,
the pair localises the change — both moving means the function itself was
edited, only the module moving means something else in the same file was. It is
never used alone, because `prepare_features` delegates to
`validate_feature_matrix` and reads `FEATURE_COLUMNS`, neither of which appears
in its own source.

| Source file | SHA-256 | Frozen because |
| --- | --- | --- |
{
        chr(10).join(
            f"| `{path}` | `{digest[:12]}…` | {policy.code_provenance.why_each_file[path]} |"
            for path, digest in policy.code_provenance.source_digests.items()
        )
    }

| Configuration / pins | SHA-256 | Frozen because |
| --- | --- | --- |
{
        chr(10).join(
            f"| `{path}` | `{digest[:12]}…` | {policy.code_provenance.why_each_file[path]} |"
            for path, digest in policy.code_provenance.configuration_digests.items()
        )
    }

**Deliberately not covered:**

{chr(10).join(f"- {item}" for item in policy.code_provenance.not_covered)}

## 9. Integrity checks

Run by `uv run python scripts/freeze_model.py --verify`, which reads the frozen
artefacts and changes nothing:

{_check_table(checks)}

All {len(checks)} checks passed. A failure of any one of them makes the command
exit non-zero, and every failure is listed at once rather than one run at a time.

### `--verify` is strictly read-only

The verification mode reads, hashes and compares. It **does not** fit, dump,
write, overwrite or repair anything, and the separation is absolute:

| `FREEZE` (no flag) | `--verify` |
| --- | --- |
| fits on the training pool | never fits |
| writes the `.joblib` | never writes |
| writes the policy and this report | never writes |
| produces the freeze | judges an existing one |

Fail-closed in every direction, and none of these is repaired automatically:

| Condition | Result |
| --- | --- |
| pipeline file absent | **FAIL** — not rebuilt |
| pipeline bytes tampered | **FAIL** — not corrected |
| model fingerprint divergent | **FAIL** — not corrected |
| policy file absent | **FAIL** — not regenerated |
| any provenance digest divergent | **FAIL** — policy not refreshed |

A verification that regenerated whatever it found missing could never fail, and a
check that cannot fail is not a check. Three independent kinds of evidence hold
this property in the test suite: writes and fits are monkeypatched to raise while
`--verify` runs to completion; every artefact's SHA-256 and mtime is compared
before and after; and an AST audit of the `verify` function asserts it references
no write or fit operation.

## 10. Reload fidelity and determinism

{reload_note}

**What is and is not claimed about determinism:**

- **Prediction determinism — verified.** The reloaded pipeline reproduces the
  probabilities of the in-memory object exactly, and a refit on the same data
  reproduces the same learned parameters bit for bit.
- **Byte-level determinism — verified in this environment, not claimed beyond
  it.** Repeated dumps of the same fitted object, and dumps of independently
  refitted objects, produced identical bytes here. `joblib` serialisation depends
  on the pickle protocol, on the numpy build and on the module paths of the
  classes involved, so a different environment may legitimately produce different
  bytes for the same model. That is precisely why `model_fingerprint_sha256`
  exists and is the authoritative check: it is invariant to all of that.

## 11. Holdout status

```text
holdout_touched: false
```

> **No holdout/test performance has been measured at this stage.**

{policy.holdout_status}.

{policy.evaluation_status}.

`load_holdout()` is not called anywhere in the Phase 9C code, and an AST audit
fails the build if it appears. The modules that do the work never load data at
all — the training pool is handed to them — so the holdout is unreachable from
them by construction rather than by discipline. The tests use synthetic fixtures
and the training pool; none of them reads a holdout row.

## 12. Limitations

- **This is a freeze, not an evaluation.** No number in this report is
  performance, because none was computed.
- **The final fit has no held-out estimate of its own**, by construction: it uses
  every row. What is known about how this configuration generalises comes from
  the cross-validated results of Phases 5 to 9B, and the only unbiased estimate
  will come from Phase 9D.
- **Byte-level reproducibility of the `.joblib` is environment-scoped**, as
  section 10 states. The model fingerprint is not.
- **`joblib.load` raises a `DeprecationWarning` from inside `joblib` itself**:
  `numpy_pickle.py` assigns to `ndarray.shape`, which numpy
  {policy.environment["numpy"]} deprecated. It comes from joblib
  {policy.environment["joblib"]} — the latest published release — not from code in
  this repository, and there is no version to upgrade to yet. It is **not
  suppressed**, per the project's warning policy. It is harmless today: the
  round-trip is verified bit-identical in section 10, and a deprecation is not a
  behaviour change. It will need a joblib release before numpy removes the
  assignment.
- **The persisted object does not validate its input.** It expects the output of
  `prepare_features()`; the validating boundary is Phase 11's subject.
- **`handle_unknown="ignore"` means an unseen category encodes as all-zeros**
  rather than raising. That is the behaviour a deployed pipeline needs, and it is
  not a substitute for detecting unseen categories — monitoring is Phase 12.
- **`class_weight` stays `{policy.model.hyperparameters["class_weight"]}` and
  stays closed.** It changes the objective the model is fitted on, so reopening
  it would reopen model selection.
- **Calibration stays `{policy.calibration.calibration_policy}`.** The threshold
  belongs to the raw probability and would have to be reselected if that changed.
- **The analyst-exposure limitation from Phase 3 still applies.**
- **Snapshot classification, not forecasting.** The dataset has no time
  dimension.

## 13. What Phase 9D receives

| Property | Value |
| --- | --- |
| Pipeline | `{artefact.pipeline_path}` (rebuild with `scripts/freeze_model.py`) |
| Model fingerprint | `{artefact.model_fingerprint_sha256[:32]}…` |
| Calibration policy | **{policy.calibration.calibration_policy}** |
| Threshold policy | **{policy.threshold.threshold_policy}** |
| `final_threshold` | **{threshold}** |
| Decision rule | `{rule.expression}` |
| Feature boundary | `{contract.entry_point}` before the pipeline |

Phase 9D verifies this policy, loads that object, applies `prepare_features` to
the holdout, scores it once, cuts at that threshold, and reports the result. It
must not refit, retune, recalibrate or move the threshold; the integrity checks
above exist so that a violation is detected rather than described.
"""


def freeze(config) -> tuple[DecisionPolicy, list[IntegrityCheck], str]:
    """Fit, persist and freeze. Returns the policy, its checks and a reload note."""
    threshold_reference = load_threshold_results()
    calibration_reference = load_calibration_results()
    tuning_reference = load_tuning_results()

    # Gates: what is frozen must be what the earlier phases decided.
    frozen = verify_frozen_candidate(tuning_reference)
    calibration_policy = verify_calibration_policy(calibration_reference)
    logger.info("Frozen candidate %s, calibration policy %s", frozen, calibration_policy)

    # From here on, only the training pool exists for this process.
    training = load_training_pool()
    features = build_feature_matrix(training)
    target = np.asarray(encode_target(training[config.target.column]))
    prevalence = positive_prevalence(target)
    logger.info("Training pool: %d rows, positive prevalence %.4f", len(features), prevalence)

    pipeline = fit_final_pipeline(features, target)
    path = dump_pipeline(pipeline)

    # Reload fidelity, on training-pool rows and without reading a single label:
    # this demonstrates serialisation, it does not evaluate anything.
    probe = features.head(RELOAD_PROBE_ROWS)
    before = positive_probability(pipeline, probe)
    reloaded = load_pipeline(path)
    after = positive_probability(reloaded, probe)
    identical = bool(np.array_equal(before, after))
    largest = float(np.max(np.abs(before - after))) if before.size else 0.0
    decisions_before = apply_decision_rule(before, threshold_reference.selection.final_threshold)
    decisions_after = apply_decision_rule(after, threshold_reference.selection.final_threshold)
    same_decisions = bool(np.array_equal(decisions_before, decisions_after))
    fingerprint_match = model_fingerprint(pipeline) == model_fingerprint(reloaded)

    reload_note = (
        f"The pipeline was written, read back, and both objects scored the same "
        f"{probe.shape[0]:,} training-pool rows. The probabilities are "
        f"{'bit-identical' if identical else 'NOT identical'} (largest absolute difference "
        f"{largest:.1e}), the decisions at the frozen threshold are "
        f"{'identical' if same_decisions else 'NOT identical'}, and the model fingerprint of the "
        f"reloaded object {'matches' if fingerprint_match else 'does NOT match'} the one written "
        f"to the policy. **No label was read and no metric was computed**: this demonstrates "
        f"serialisation fidelity, not performance."
    )
    if not (identical and same_decisions and fingerprint_match):
        raise IntegrityError(
            "The reloaded pipeline does not reproduce the in-memory one. "
            f"probabilities identical={identical}, decisions identical={same_decisions}, "
            f"fingerprint match={fingerprint_match}."
        )

    digests = {artefact: file_digest(PROJECT_ROOT / artefact) for artefact in UPSTREAM_ARTEFACTS}
    policy = build_decision_policy(
        pipeline,
        path,
        threshold_reference,
        calibration_reference,
        tuning_reference,
        len(features),
        prevalence,
        digests,
    )
    write_decision_policy(policy)

    # Self-check: the record just written must pass the same verification the
    # --verify command runs, or it is not a freeze anybody can rely on.
    checks, _ = verify_or_raise(load_decision_policy(), threshold_reference, calibration_reference)
    logger.info("Freeze verified: %d integrity checks passed.", len(checks))
    return policy, checks, reload_note


def verify(policy_path: Path | None = None, root: Path | None = None) -> int:
    """Verify an existing freeze. **Strictly read-only.** Returns an exit code.

    This function reads, hashes and compares. It does not fit, dump, write or
    repair, and that is a guarantee rather than a description: a verification
    that regenerated whatever it found missing could never fail, and a check that
    cannot fail is not a check.

    Fail-closed in every direction. A missing pipeline is a failure, not a
    trigger to rebuild it. A divergent fingerprint is a failure, not something to
    correct in place. A divergent provenance digest is a failure, not a reason to
    refresh the policy.

    Args:
        policy_path: Freeze record to verify. Defaults to the real one.
        root: Repository root for resolving the pipeline and the source files.
            Both parameters exist so the fail-closed behaviour can be exercised
            against temporary copies without touching one real artefact.

    Returns:
        ``0`` if every check passed, ``1`` otherwise.
    """
    policy = load_decision_policy(policy_path)
    checks, _ = verify_decision_policy(
        policy, load_threshold_results(), load_calibration_results(), root
    )
    for check in checks:
        logger.log(
            logging.INFO if check.passed else logging.ERROR,
            "%s %s: %s",
            "PASS" if check.passed else "FAIL",
            check.name,
            check.detail,
        )

    failed = [check for check in checks if not check.passed]
    if failed:
        logger.error("%d of %d integrity checks FAILED.", len(failed), len(checks))
        return 1
    logger.info("All %d integrity checks passed.", len(checks))
    logger.info(
        "Frozen policy: %s at threshold %r, calibration %s",
        policy.threshold.threshold_policy,
        policy.threshold.final_threshold,
        policy.calibration.calibration_policy,
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the freeze, or verify an existing one. Returns a process exit code."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--verify",
        action="store_true",
        help="check the existing freeze and change nothing",
    )
    arguments = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    config = get_config()

    try:
        verify_split_manifest(load_split_manifest())
        if arguments.verify:
            return verify()
        policy, checks, reload_note = freeze(config)
    except FileNotFoundError as error:
        logger.error("%s", error)
        return 1
    except RawDatasetMismatchError as error:
        logger.error("%s", error)
        return 2
    except SplitManifestMismatchError as error:
        logger.error("%s", error)
        return 3
    except FrozenCandidateMismatchError as error:
        logger.error("%s", error)
        return 4
    except CalibrationPolicyMismatchError as error:
        logger.error("%s", error)
        return 5
    except IntegrityError as error:
        logger.error("%s", error)
        return 6

    Path(REPORT_PATH).write_text(
        build_report(policy, checks, reload_note),
        encoding="utf-8",
        newline="\n",
    )
    logger.info("Wrote %s", REPORT_PATH)
    logger.info("Wrote %s", POLICY_PATH)
    logger.info("Wrote %s", PIPELINE_PATH)
    logger.info(
        "Frozen: %s, calibration %s, threshold %r",
        policy.model.estimator,
        policy.calibration.calibration_policy,
        policy.threshold.final_threshold,
    )
    logger.info("Model fingerprint: %s", policy.artifacts.model_fingerprint_sha256)
    return 0


if __name__ == "__main__":
    sys.exit(main())
