"""Fit the preprocessing pipeline on the training pool and write the Phase 4 report.

Usage (from the repository root):

    uv run python scripts/build_split.py        # first: freeze the split
    uv run python scripts/run_preprocessing.py

Writes:
    reports/preprocessing_report.md

The holdout is never loaded here. The script reaches the data through
``load_training_pool``, which discards the holdout before returning, and takes
the holdout row count from the manifest — a structural fact, not a statistic.
No model is trained.
"""

from __future__ import annotations

import logging
import sys
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline

from churn.config import PROJECT_ROOT, get_config
from churn.data.loader import RawDatasetMismatchError
from churn.preprocessing.contracts import (
    CATEGORICAL_FEATURES,
    FEATURE_COLUMNS,
    ID_COLUMN,
    NUMERIC_FEATURES,
    build_feature_matrix,
)
from churn.preprocessing.manifest import (
    MANIFEST_PATH,
    SplitManifest,
    SplitManifestMismatchError,
    load_split_manifest,
    verify_split_manifest,
)
from churn.preprocessing.pipeline import (
    CATEGORICAL_STEP,
    ENCODER_STEP,
    build_preprocessor,
    feature_names_out,
)
from churn.preprocessing.splitting import load_training_pool
from churn.preprocessing.target import encode_target

logger = logging.getLogger("run_preprocessing")

REPORT_PATH = PROJECT_ROOT / "reports" / "preprocessing_report.md"


def _bullets(names: tuple[str, ...]) -> str:
    return "\n".join(f"- `{name}`" for name in names)


def _category_rows(preprocessor: Pipeline) -> str:
    encoder = preprocessor.named_steps[ENCODER_STEP].named_transformers_[CATEGORICAL_STEP]
    return "\n".join(
        f"| `{column}` | {len(categories)} | "
        + ", ".join(f"`{value}`" for value in categories)
        + " |"
        for column, categories in zip(CATEGORICAL_FEATURES, encoder.categories_, strict=True)
    )


def build_report(
    manifest: SplitManifest,
    matrix: pd.DataFrame,
    preprocessor: Pipeline,
    names: list[str],
    generated_on: str,
) -> str:
    """Render the Phase 4 report. Every number comes from this run."""
    n_categorical_out = len(names) - len(NUMERIC_FEATURES)
    numeric_list = ", ".join(f"`{name}`" for name in NUMERIC_FEATURES)
    n_raw_columns = len(FEATURE_COLUMNS) + 2

    return f"""# Preprocessing Protocol — Telco Customer Churn (Phase 4)

- Generated on: {generated_on}
- Generated by: `scripts/run_preprocessing.py`; the split is frozen by
  `scripts/build_split.py` and recorded in `reports/split_manifest.json`.
- Every number below was produced by this run **on the training pool only**.

---

## 1. Objective

Turn the raw file into a reproducible, leakage-safe modeling protocol, without
training anything. Concretely: freeze the partition before any transformation,
declare which columns may reach a model, decide the one genuine data-quality
question the dataset poses, and package the numeric/categorical handling as a
pipeline whose fitted state can only come from training data.

Nothing here is a modeling result. No estimator is fitted beyond the scaler and
the encoder, and no metric exists yet.

## 2. Dataset fingerprint

| Property | Value |
| --- | --- |
| File | `{manifest.raw_filename}` |
| SHA-256 | `{manifest.raw_sha256}` |
| Rows | {manifest.n_rows_total:,} |
| Identifier | `{manifest.id_column}` |
| Target | `{manifest.target_column}` |

The digest is checked before the split runs. A file that does not match the one
approved in Phase 2 raises `RawDatasetMismatchError`, because a different file
would silently produce a different partition while every recorded number kept
claiming otherwise.

## 3. Split strategy

The split is the **first** operation applied to the raw data. Nothing is
coerced, imputed, encoded or scaled before it.

| Parameter | Value | Source |
| --- | --- | --- |
| Function | `{manifest.split_function}` | — |
| `test_size` | {manifest.test_size} | `configs/base.toml` |
| `random_state` | {manifest.random_state} | `configs/base.toml` (`random.seed`) |
| `shuffle` | {manifest.shuffle} | fixed |
| Stratification | `{manifest.stratified_by}` | `configs/base.toml` (`split.stratify`) |
| scikit-learn | {manifest.scikit_learn_version} | environment |

| Partition | Rows |
| --- | --- |
| Training pool | {manifest.n_rows_training:,} |
| Holdout | {manifest.n_rows_holdout:,} |
| Total | {manifest.n_rows_total:,} |

Stratification by the target is not cosmetic here: at a 26.5% positive rate a
purely random 20% draw can shift the positive share by a full percentage point,
which would make the final estimate partly a sampling artifact.

### Freezing, not storing

Neither partition is written to disk and no identifier list is versioned. What
is versioned is `reports/split_manifest.json`, which records the raw digest,
every split parameter, the row counts and a SHA-256 over the **sorted**
identifiers of each partition. Sorting before hashing makes the digest a
property of the *set* of rows rather than of the order `train_test_split`
emitted them.

That is enough to regenerate the partition and prove it is the same one:

```bash
uv run python scripts/build_split.py --verify
```

| Fingerprint | Value |
| --- | --- |
| Training IDs SHA-256 | `{manifest.training_ids_sha256}` |
| Holdout IDs SHA-256 | `{manifest.holdout_ids_sha256}` |

Structural checks run on every regeneration: unique identifiers inside each
partition, no overlap between them, and a union that reproduces the source
dataset exactly.

## 4. Holdout protection

From this phase until Phase 9 the holdout is used for **nothing**.

- `load_training_pool()` regenerates the split and discards the holdout before
  returning. It is the entry point for Phases 4 to 8.
- `load_holdout()` exists because Phase 9 needs it, is **not** exported by
  `churn.preprocessing`, and logs a warning when it runs. Using it requires
  importing `churn.preprocessing.splitting` by name, which shows up in a diff.
- Only structural facts about the holdout appear in this report: its row count
  and its identifier fingerprint. No churn rate, no feature distribution, no
  summary statistic, no figure.

This is a discipline enforced by code layout and review, not a hard guarantee —
anyone can import the module. The point is to make holdout access deliberate and
visible rather than accidental.

## 5. Inherited limitation: analyst exposure

Phase 3 ran on all {manifest.n_rows_total:,} rows, holdout included. The
consequence carries into this phase and must stay on the record:

- No fitting, preprocessing, selection or tuning was done in Phase 3; nothing was
  learned in a form a model could inherit.
- **But** the hypotheses and candidate features from the EDA were informed by the
  complete dataset. The `TotalCharges` rule in section 9 is itself a decision
  taken with knowledge of the full file.
- The holdout is therefore protected from *fitting and tuning*, not *unseen*. The
  final estimate may carry optimistic bias from analyst exposure; how much cannot
  be quantified here, because no independent sample exists to measure it against.
- Avoiding this would have required splitting before any exploration. That
  alternative was available and was not chosen; recording the cost is the
  honest response, not a correction factor.

## 6. Feature contract

The contract is declared, not inferred from the file. A schema derived from
whatever is on disk cannot notice that the disk changed.

**Numeric ({len(NUMERIC_FEATURES)})**

{_bullets(NUMERIC_FEATURES)}

**Categorical ({len(CATEGORICAL_FEATURES)})**

{_bullets(CATEGORICAL_FEATURES)}

`SeniorCitizen` is listed as categorical although the CSV stores it as `0`/`1`.
It is a binary flag, not a quantity; routing it through the one-hot encoder keeps
any notion of magnitude or ordering out of the model.

**Excluded, by contract**

| Column | Reason |
| --- | --- |
| `{ID_COLUMN}` | Unique per row. A model can only memorize it. Used for split \
integrity and fingerprints, never as a feature. |
| `{manifest.target_column}` | The target. Its presence in the matrix would be total leakage. |

**Validation rejects**: a missing contracted feature, an undeclared extra column,
the identifier, the target, a column declared numeric that is not, and any
unexpected blank (section 7).

**Column order is not part of the contract.** A caller has no reason to preserve
one — a JSON payload has no inherent order — so `prepare_features()` accepts the
features in any order and returns them in the canonical `FEATURE_COLUMNS` order.
Everything downstream, training and inference alike, receives that canonical
representation. This matters because the transformed output is a positional
array: without normalization, a reordered payload would silently feed the model
the wrong columns. Tests pin that a shuffled input produces a byte-identical
transformed matrix.

`prepare_features()` is the mandatory entry point. The persisted pipeline does
not re-validate the schema itself, so any inference path added in Phase 11 must
route its input through it.

## 7. Missing and blank policy

Nothing in this pipeline imputes. A blank that survived validation would either
propagate as `NaN` through the scaler or be silently absorbed by the encoder's
`handle_unknown="ignore"` — in both cases turning a data problem into a quiet
degradation of the prediction. So blanks are rejected at the contract boundary.

| Case | Result |
| --- | --- |
| `tenure` missing | `DataQualityError` |
| `MonthlyCharges` missing | `DataQualityError` |
| categorical `None` / `NaN` | `DataQualityError` |
| categorical `""` | `DataQualityError` |
| categorical whitespace-only | `DataQualityError` |
| `TotalCharges` blank, `tenure == 0` | `0.0` (the one structural exception, section 9) |
| `TotalCharges` blank, `tenure > 0` | `DataQualityError` |
| `TotalCharges` non-numeric | `DataQualityError`, whatever `tenure` says |
| `No internet service` / `No phone service` | **accepted** — real product states |

The last row is the distinction that matters. The EDA measured markedly
different churn rates for those sentinel categories; treating them as missing
would destroy information, not clean it. They are ordinary strings and pass
validation untouched.

`handle_unknown="ignore"` remains in place for its actual purpose — a genuinely
new, valid category appearing after training — and is never the mechanism by
which a blank reaches the model.

## 8. Target encoding

| Label | Encoded |
| --- | --- |
| `{manifest.negative_label}` | 0 |
| `{manifest.positive_label}` | 1 |

`encode_target()` accepts only these two labels and raises
`UnknownTargetLabelError` otherwise, missing values included — a silent `NaN`
would encode as `0` and invent a negative case. The mapping comes from
`configs/base.toml`; no encoder learns it from the data, because a learned
mapping would accept a relabeled file and flip the meaning of every metric that
follows. The input Series is not modified; a new `int8` Series is returned.

## 9. `TotalCharges` decision

**What the data show** (Phases 2 and 3): 11 whitespace-only cells, and the
customers holding them are *exactly* the 11 with `tenure == 0`. The sets
coincide; there is no unreadable cell at positive tenure.

**Rule implemented**

1. strip surrounding whitespace;
2. coerce to a number;
3. blank **and** `tenure == 0` → `0.0`;
4. anything else unreadable → `DataQualityError`.

**Why `0.0`.** `TotalCharges` is an accumulated amount. A customer who has not
completed a billing cycle has accumulated nothing, so zero is the value the
quantity actually takes. No distribution is estimated and nothing is learned from
the data, which is why the step can sit before the split boundary without
leaking: it is arithmetic, not inference. A median imputation would assert a
billing history that does not exist.

**Scope of the claim.** This is a domain decision grounded in the pattern
observed in *this* dataset, not a universal rule for telecom data. In a file
where blanks appeared at positive tenure, a blank would mean "unknown", not
"never billed", and this rule would be wrong. Step 4 exists so that such a file
fails loudly instead of being silently repaired.

Structural blank `TotalCharges` values present in the training pool are handled
by the deterministic `tenure == 0` rule. No count is published: combined with the
11 cases already documented in the EDA, a per-partition tally would reveal the
holdout's by subtraction, and the holdout carries no published statistic in this
project before Phase 9.

**Behaviour on invalid data** — all raise, none imputes:

| Input | `tenure` | Result |
| --- | --- | --- |
| `" "` / missing | `0` | `0.0` (structural zero) |
| `" "` / missing | `> 0` | `DataQualityError` |
| non-numeric text | any | `DataQualityError` |
| unreadable `tenure` | — | `DataQualityError` |

## 10. Numeric preprocessing

`StandardScaler` on {numeric_list}, fitted on the training
pool only. Standardization is not required by tree-based models but is required
by regularized linear models, whose penalty is scale-dependent; a single shared
pipeline keeps the comparison in Phase 7 honest.

**No statistical imputation is configured.** After the structural rule above the
approved dataset carries no genuine numeric missingness, so an imputer would have
nothing to do except hide an unexpected gap. An unexpected gap fails through the
contract instead (section 7), rather than being masked by a median.

## 11. Categorical preprocessing

`OneHotEncoder(handle_unknown="ignore", sparse_output=False)`, fitted on the
training pool only.

- **No ordinal encoding**: none of these variables carries an order, and an
  arbitrary integer would invent one.
- **No target encoding**: it reads the target while building a feature, which is
  the textbook leakage pattern.
- **No frequency encoding**: it injects a statistic of the fitting sample into
  each row for no stated hypothesis.
- **No collapsing of `No internet service` / `No phone service`**: the EDA showed
  these are real product states with distinct churn rates, not missing data.
- `handle_unknown="ignore"` encodes an unseen category as all-zeros instead of
  raising at prediction time — the behaviour a deployed pipeline needs for a
  genuinely new, valid category. Detecting unseen categories is a monitoring
  concern, designed in Phase 12; ignoring them at serving time is not a
  substitute for detecting them. It is **not** the mechanism by which a blank
  reaches the model: blanks are rejected earlier, at the contract (section 7).
- Dense output: the matrix is about {len(matrix):,} x {len(names)} here, so
  sparsity buys nothing while a dense array keeps downstream estimators,
  explainers and serialization simple.

Categories learned from the training pool:

| Feature | Levels | Values |
| --- | --- | --- |
{_category_rows(preprocessor)}

## 12. Dimensionality

| Stage | Columns |
| --- | --- |
| Raw file | {n_raw_columns} (incl. `{ID_COLUMN}` and `{manifest.target_column}`) |
| Feature matrix (contract) | {len(FEATURE_COLUMNS)} |
| After transformation | {len(names)} ({len(NUMERIC_FEATURES)} scaled numeric + \
{n_categorical_out} one-hot indicators) |

Transformed feature names are available through `feature_names_out()`, which is
what Phase 10 will need to attach coefficients and importances to something a
reader can interpret.

## 13. Leakage controls

| Control | Mechanism |
| --- | --- |
| Split precedes every transformation | `split_dataset()` receives the untouched raw frame |
| Fitted state comes from training only | `StandardScaler` and `OneHotEncoder` live \
inside the pipeline; `fit` is only ever called on the training pool or a CV training fold |
| Holdout not reachable by accident | `load_training_pool()` discards it; \
`load_holdout()` is unexported and logs a warning |
| Identifier cannot become a feature | Rejected by `validate_feature_matrix()`, \
covered by a regression test |
| Target cannot become a feature | Rejected by `validate_feature_matrix()`, \
covered by a regression test |
| Column order cannot change meaning | `prepare_features()` normalizes to the \
canonical order after validating |
| Blanks cannot degrade a prediction silently | Rejected at the contract; nothing \
is imputed anywhere (section 7) |
| Target mapping cannot drift | Declared in configuration, never learned |
| `TotalCharges` rule learns nothing | Pure arithmetic; identical at train, CV and inference time |
| Partition cannot drift unnoticed | Manifest fingerprints, verified by `--verify` and by tests |

The pipeline is a `Pipeline`/`ColumnTransformer` precisely so that Phase 7's
cross-validation refits every fitted component inside each fold. Fitting the
scaler or the encoder once on the whole training pool before cross-validation
would leak validation-fold information into every fold.

## 14. Decisions deferred

| Decision | Phase |
| --- | --- |
| Engineered features (protective-service count, tenure × contract, charge \
intensity, `TotalCharges / tenure`, automatic-payment flag) | 6 |
| Whether `TotalCharges` is kept at all, given how closely it tracks \
`tenure × MonthlyCharges` | 6–7 |
| Class-imbalance handling (weights, resampling) | 7 |
| Model selection and tuning | 7–8 |
| Decision threshold, calibration, cost framing | 9 |
| Persisted inference pipeline **and its validating entry point** (see below) | 11 |

None of the EDA's candidate features is implemented here. Phase 4 works with the
original columns only; a candidate must earn its place through cross-validation
on the training pool, not through a number in the EDA report.

### Carried requirement for Phase 11

The persisted `Pipeline` does **not** validate its own input. It assumes the
canonical, contract-checked representation that `prepare_features()` produces.
A raw payload handed straight to it would bypass every guarantee in sections 6
and 7: a `NaN` would flow through the scaler, an unexpected column would be
dropped in silence, and a reordered payload would be read positionally.

Therefore, in Phase 11:

- the inference interface **must** run `prepare_features()` — validation plus
  canonicalization — before calling the persisted pipeline;
- `pipeline.predict()` / `predict_proba()` **must not** be treated as a public
  interface for unvalidated raw payloads;
- the entry point that fulfils this requirement is what gets tested and
  documented as the prediction API, not the pipeline object itself.

This is a deliberate boundary, not an oversight: keeping validation outside the
estimator keeps the pipeline a pure transformation, which is what makes it safe
to refit inside every cross-validation fold in Phase 7.

## 15. Limitations

- **The `TotalCharges` rule is dataset-specific.** It is justified by the exact
  overlap between blanks and `tenure == 0` in this file and nowhere else.
- **`handle_unknown="ignore"` degrades silently by design.** An unseen category
  becomes an all-zero block, which is indistinguishable from a legitimately
  absent level at prediction time. Monitoring must catch it; the encoder cannot.
- **Standardization assumes the training pool represents deployment.** The
  dataset carries no time dimension, so no drift in the scaler's statistics can
  be observed here.
- **Analyst exposure (section 5)** remains an unquantifiable source of optimistic
  bias in the future holdout estimate.
- **No validation of the preprocessing choices yet.** Nothing in this phase has
  been shown to help a model; only that it is reproducible, contract-checked and
  free of the leakage patterns listed in section 13.
"""


def main() -> int:
    """Fit the preprocessor on the training pool and write the report."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    config = get_config()

    try:
        manifest = verify_split_manifest(load_split_manifest())
    except FileNotFoundError as error:
        logger.error("%s", error)
        return 1
    except RawDatasetMismatchError as error:
        logger.error("%s", error)
        return 2
    except SplitManifestMismatchError as error:
        logger.error("%s", error)
        return 3

    # From here on, only the training pool exists for this process.
    training = load_training_pool()
    matrix = build_feature_matrix(training)
    target = encode_target(training[config.target.column])

    preprocessor = build_preprocessor()
    preprocessor.fit(matrix, target)
    transformed = preprocessor.transform(matrix)
    names = feature_names_out(preprocessor)

    if np.isnan(transformed).any():
        logger.error("Transformed training matrix contains NaN — preprocessing is incomplete.")
        return 4

    logger.info(
        "Training matrix transformed: %d rows, %d raw features -> %d transformed features",
        transformed.shape[0],
        matrix.shape[1],
        transformed.shape[1],
    )

    report = build_report(manifest, matrix, preprocessor, names, date.today().isoformat())
    Path(REPORT_PATH).write_text(report, encoding="utf-8", newline="\n")
    logger.info("Wrote %s", REPORT_PATH)
    logger.info("Split manifest: %s", MANIFEST_PATH)
    return 0


if __name__ == "__main__":
    sys.exit(main())
